### ISSUE TITLE
Parallelize buffering via `furrr`

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/spatialsample#100]
## Feature

Buffering takes a _while_. For making one rset, it's not that bad, but when making multiple (particularly with many rsplits) it becomes a huge timesink. The process is almost entirely CPU limited.

That said, we apply buffering to each rsplit completely independently (buffers in one resample are irrelevant to the next). I think one way to dramatically speed up this process would be to change this line from `purrr` to `furrr`, enabling users to parallelize buffering via `future`:
https://github.com/tidymodels/spatialsample/blob/02a654adcecbb6e05bcbf532692350fba4e842cc/R/buffer.R#L47

The downside is that if this is inside of _other_ parallel workflows (for instance, inside a targets script that's already using `future`) it could wind up causing problems. 

What do others think?

**Comment by juliasilge** [comment]
We've said no to parallelizing some parts of tidymodels, like an individual recipe step in most cases as outlined in tidymodels/recipes#48. This is because it's generally best to parallelize over resamples. What you are saying here is different because it involves using parallelism to _create_ the resamples, which I don't think would be any more of a problem than our other uses of parallelism in tune.

You can see [this way that baguette uses furrr optionally](https://github.com/tidymodels/baguette/blob/main/R/misc.R#L96-L103). Typically rsets don't have a `control` option like models in tidymodels. Should we add one? Or maybe just a plain argument like `allow_parallel`?

**Comment by mikemahoney218** [comment]
I think it would definitely make sense to gate this behind an argument! `allow_parallel` makes sense.

I think I probably ID'd the wrong `map` to change -- profvis says most of our time actually happens here:
https://github.com/tidymodels/spatialsample/blob/02a654adcecbb6e05bcbf532692350fba4e842cc/R/buffer.R#L69-L76

**Comment by mikemahoney218** [comment]
Hmm, maybe not as easy/lightweight a change as I expected -- changing either of those to `furrr` actually makes things take longer, on my machine. Will investigate further though!

**Comment by mikemahoney218** [comment]
Parallelizing turned out not to be easy low hanging fruit, but moving to C++ did. Going to close this as wontfix for the time being, and we can return later if anyone complains.
